image: gradle:jdk17

stages:
  - build
  - test
  - package
  # - deploy

services:
  - name: docker:dind
    command: [ "--tls=false" ]

variables:
  CUSTOMER_INFORMATION_SERVICE_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/customer-information-service:latest
  DEPOT_SERVICE_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/depot-service:latest
  LOGIN_SERVICE_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/login-service:latest
  SUPPORT_SERVICE_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/support-service:latest
  TRANSACTION_SERVICE_IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/transaction-service:latest
  CI_REGISTRY: "git.ai.fh-erfurt.de"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_HOST: "tcp://docker:2375"  # Uses TCP connection to Docker Daemon
  DOCKER_TLS_CERTDIR: ""  # Disables TLS certificate directory
  DOCKER_DRIVER: overlay2

before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"

##### Customer Information Service Start #####
build-customer-information-service:
  stage: build
  script:
    - cd customer-information-service
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - customer-information-service/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: customer-information-service/build/test-results/test/**/TEST-*.xml

build-customer-information-service-image:
  stage: package
  image: docker:stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd customer-information-service
    - docker build -f src/main/docker/Dockerfile.jvm -t $CUSTOMER_REVIEW_SERVICE_IMAGE_NAME .
    # - docker push $CUSTOMER_REVIEW_SERVICE_IMAGE_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - customer-information-service/build
      - .gradle
  dependencies:
    - build-customer-information-service
##### Customer Information Service End #####

##### Depot Service Start #####
build-depot-service:
  stage: build
  script:
    - cd depot-service
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - depot-service/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: depot-service/build/test-results/test/**/TEST-*.xml

build-depot-service-image:
  stage: package
  image: docker:stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd depot-service
    - docker build -f src/main/docker/Dockerfile.jvm -t $DEPOT_SERVICE_IMAGE_NAME .
    # - docker push $DEPOT_SERVICE_IMAGE_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - depot-service/build
      - .gradle
  dependencies:
    - build-depot-service
##### Depot Service End #####

##### Login Service Start #####
build-login-service:
  stage: build
  script:
    - cd login-service
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - login-service/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: login-service/build/test-results/test/**/TEST-*.xml

build-login-service-image:
  stage: package
  image: docker:stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd login-service
    - docker build -f src/main/docker/Dockerfile.jvm -t $LOGIN_SERVICE_IMAGE_NAME .
    # - docker push $LOGIN_SERVICE_IMAGE_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - login-service/build
      - .gradle
  dependencies:
    - build-login-service
##### Login Service End #####

##### Support Service Start #####
build-support-service:
  stage: build
  script:
    - cd support-service
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - support-service/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: support-service/build/test-results/test/**/TEST-*.xml

build-support-service-image:
  stage: package
  image: docker:stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd support-service
    - docker build -f src/main/docker/Dockerfile.jvm -t $SUPPORT_SERVICE_IMAGE_NAME .
    # - docker push $SUPPORT_SERVICE_IMAGE_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - support-service/build
      - .gradle
  dependencies:
    - build-support-service
##### Support Service End #####

##### Transaction Service Start #####
build-transaction-service:
  stage: build
  script:
    - cd transaction-service
    - echo "testcontainers.reuse.enable=true" > /root/.testcontainers.properties
    - gradle build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - transaction-service/build
      - .gradle
  artifacts:
    when: always
    reports:
      junit: transaction-service/build/test-results/test/**/TEST-*.xml

build-transaction-service-image:
  stage: package
  image: docker:stable
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  script:
    - cd transaction-service
    - docker build -f src/main/docker/Dockerfile.jvm -t $TRANSACTION_SERVICE_IMAGE_NAME .
    # - docker push $TRANSACTION_SERVICE_IMAGE_NAME
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - transaction-service/build
      - .gradle
  dependencies:
    - build-transaction-service
##### Transaction Service End #####
