{
 "title": "Login Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max Server Request By Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"login-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Server Request By Second",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"login-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Server Request By Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"login-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of Server Request By Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"login-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}