{
 "title": "Support-Service",
 "description": "Visualization of support-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successfull Support Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{job=\"aurumbanking-services\", status=~\"200\", instance=\"support-service:8080\"}) or sum(http_server_requests_seconds_count{job=\"aurumbanking-services\", status=~\"4..|5..\", instance=\"support-service:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Of Support Requests Per Second Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"support-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messaurment of Max Request-Time 201",
   "type": "timeseries",
   "description": "HTTP server request processing time 201",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"aurumbanking-services\", status=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messaurment of Max Request-Time 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{status=\"200\", instance=\"support-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_connections_seconds_duration_sum{instance=\"support-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messaurment of Max Request-Time 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"aurumbanking-services\", status=\"200\", instance=\"support-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}