{
 "title": "Transaction-Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Messaurment of Max Request-Time 201",
   "type": "timeseries",
   "description": "HTTP server request processing time 201",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"aurumbanking-services\", status=\"201\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count All - 201 Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"transaction-service:8080\", status=\"201\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messaurment of Max Request-Time 201",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"aurumbanking-services\", status=\"201\", instance=\"transaction-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messaurment of Max Request-Time 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{status=\"200\", instance=\"transaction-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}