###
POST http://localhost:8080/depot
Accept: application/json
Content-Type: application/json

{
  "customerId": 1,
  "currencyArea": "EUR",
  "depositAmount": 5000.00,
  "fallbackDepositAmount": 1000.00
}

###
GET http://localhost:8080/depot/findCurrentDepotValueById/1


###
PUT http://localhost:8080/depot/insertNewDepositValueById/1/7000.45

###
DELETE http://localhost:8080/depot/deleteDepotBy/1


###
POST http://localhost:80/depot-service/depot
Accept: application/json
Content-Type: application/json

{
  "customerId": 1,
  "currencyArea": "EUR",
  "depositAmount": 5000.00,
  "fallbackDepositAmount": 1000.00
}

###
GET http://localhost:80/depot-service/depot/1

###
PUT http://localhost:80/depot-service/depot/insertNewDepositValueById/1/7000.45

###
GET http://localhost:80/depot-service/depot/findCurrentDepotValueById/1













