### generate token endpoint before create customer
GET http://{{ip}}:{{port}}/{{customer-information-service-jwt-token-fullpath}}
Authorization: Basic Hoang admin


### Customer-Information
POST http://{{ip}}:{{port}}/{{customer-information-service-fullpath}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FpLmZoLWVyZnVydC5kZSIsInN1YiI6IkhvYW5nIiwiaWF0IjoxNzI0NDM1MjgwLCJleHAiOjE3MjQ0Mzg4ODAsImdyb3VwcyI6WyJhZG1pbiJdLCJsZXZlbC1vZi1uZXJkaW5lc3MiOjQyLCJqdGkiOiI0ZTBmODVmZC1jYzllLTQxOWMtOGM4OC1kNDhlMWJiNDUwODkifQ.hYOwJMKJGvYXrGSE0h8p8Kqt3HDR83MlRUxnLyFz376Tt4ibILgOp2OE-lzxH75dxDI3qGXnpx-MgKho-7R5cJIvzz3SvgiDxfiyYtLo3gZLS-bB_4NbTie6Rk7QnniUSyXqvjzTE5JDK6x60aBXFBwKJpKMHI4goJQgie_ucDUpBrE1h4NpFpF5uIcJ_qkMy1GWiLZboYeERwNNqyu8hj5Z5vYmG6SrlqY8WQf95BvQsqOJj_aFjXAdMp3_ffejHSIbGe85yzzLKFMvh-AwBfJuJ7zFjn_N3e3Dl051WxFMc5ovHEIhFyqaH-58Yik5ASYX84LRw206hrxt1I16mA
# fill token into Baerer xyz

{
  "firstname": "John",
  "lastname": "Doe",
  "birthDate": "1990-01-01T00:00:00",
  "created": "2024-05-30T14:00:00",
  "lastestLogin": "2024-05-30T14:00:00",
  "streetName": "Main Street",
  "housenumber": "123",
  "city": "Sample City",
  "country": "Sample Country",
  "zipcode": "DE176381",
  "username": "johndoe",
  "email": "johndoe@example.com",
  "phoneNumber": "+1234567890",
  "password": "123",
  "profileImage": "{{profilImage}}"
}

###
GET http://{{ip}}:{{port}}/{{customer-information-service-fullpath}}/1

### Login
POST http://{{ip}}:{{port}}/{{login-service-fullpath}}/johndoe@example.com/123

### Depot
POST http://{{ip}}:{{port}}/{{depot-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "customerId": 1,
  "currencyArea": "EUR",
  "depositAmount": 5000.00,
  "fallbackDepositAmount": 1000.00
}


###
GET http://{{ip}}:{{port}}/{{depot-service-fullpath}}/1


### Transactions
POST http://{{ip}}:{{port}}/{{transaction-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "John Doe",
  "iban": "DE89370400440532013000",
  "bic": "COBADEFFXXX",
  "moneyValue": 1000.00,
  "purposeOfUse": "Payment for services",
  "standingOrder": false,
  "transactionType": "outcome",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

###
POST http://{{ip}}:{{port}}/{{transaction-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "Master of Disaster",
  "iban": "DE89370400440532013XXX",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Income42",
  "standingOrder": true,
  "transactionType": "income",
  "transactionClassification": "Dauerauftrag",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

###
GET http://{{ip}}:{{port}}/{{transaction-service-fullpath}}/getTransactionById/1


###
GET http://{{ip}}:{{port}}/{{transaction-service-fullpath}}/getThreeLatestTransactionByDepotId/1



