
### Customer-Information
POST http://{{ip}}:{{port}}/{{customer-information-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "birthDate": "1990-01-01T00:00:00",
  "created": "2024-05-30T14:00:00",
  "lastestLogin": "2024-05-30T14:00:00",
  "streetName": "Main Street",
  "housenumber": "123",
  "city": "Sample City",
  "country": "Sample Country",
  "username": "johndoe",
  "email": "johndoe@example.com",
  "phoneNumber": "+1234567890",
  "password": "123",
  "profileImage": "iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAIAAAD/gAIDAAAAEklEQVR4nO3BMQEAAADCoPdPbQ43oAAAAABJRU5ErkJggg=="
}

###
GET http://{{ip}}:{{port}}/{{customer-information-service-fullpath}}/1

### Login
POST http://{{ip}}:{{port}}/{{login-service-fullpath}}/johndoe@example.com/123

### Depot
POST http://{{ip}}:{{port}}/{{depot-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "customerId": 1,
  "currencyArea": "EUR",
  "depositAmount": 5000.00,
  "fallbackDepositAmount": 1000.00
}


###
GET http://{{ip}}:{{port}}/{{depot-service-fullpath}}/1


### Transactions
POST http://{{ip}}:{{port}}/{{transaction-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "John Doe",
  "iban": "DE89370400440532013000",
  "bic": "COBADEFFXXX",
  "moneyValue": 1000.00,
  "purposeOfUse": "Payment for services777",
  "dateTimeOfExecution": "2024-06-12T10:04:00Z",
  "standingOrder": false,
  "transactionType": "outcome",
  "transactionClassification": "Standard Überweisung"
}

###
POST http://{{ip}}:{{port}}/{{transaction-service-fullpath}}
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "Master of Disaster",
  "iban": "DE89370400440532013XXX",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Testo555",
  "dateTimeOfExecution": "2024-09-01T00:00:00",
  "standingOrder": true,
  "transactionType": "income",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

###
GET http://{{ip}}:{{port}}/{{transaction-service-fullpath}}/getThreeLastestTransactionByDepotId/1



