### Erstellen von Datensätzen

POST http://localhost:8080/support
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "customerId": 0,
  "dateTime": "2024-06-06T00:00:00",
  "type": "exampleType",
  "message": "exampleMessage"
}
###
POST http://localhost:8080/support
Accept: application/json
Content-Type: application/json

{
"id": 0,
"customerId": 1,
"dateTime": "2024-06-07T08:00:00",
"type": "exampleType1",
"message": "This is an example message for type exampleType1."
}
###
POST http://localhost:8080/support
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "customerId": 1,
  "dateTime": "2024-06-07T08:00:00",
  "type": "exampleType2",
  "message": "This is an example message for type exampleType1."
}

###
GET http://localhost:8080/support/1
Content-Type: application/json

###
GET http://localhost:8080/support/get-all-support-reqeuests-by-type/exampleType1
Accept: application/json

###
GET http://localhost:8080/support/get-all-support-reqeuests-by-customer-id/0
Accept: application/json

###
DELETE http://localhost:8080/support/deleteRequestByCustomerId/1

###
POST http://localhost:80/support-service/support
Accept: application/json
Content-Type: application/json

{
"id": 0,
"customerId": 0,
"dateTime": "2024-06-06T00:00:00",
"type": "exampleType",
"message": "exampleMessage"
}


###
GET http://localhost:80/support-service/support/1
Content-Type: application/json

###
GET http://localhost:80/support-service/support/test
Content-Type: application/json
