### DEV
POST http://localhost:8081/transactions
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "John Doe",
  "iban": "DE89370400440532013000",
  "bic": "COBADEFFXXX",
  "moneyValue": 2000.00,
  "purposeOfUse": "Payment for services",
  "standingOrder": false,
  "transactionType": "outcome",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

### DEV
POST http://localhost:8081/transactions
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "Master of Disaster",
  "iban": "DE89370400440532013XXX",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Stuff",
  "standingOrder": true,
  "transactionType": "income",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

### DEV
POST http://localhost:8081/transactions/
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "John Doe",
  "iban": "DE89370400440532013000",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Rent",
  "standingOrder": true,
  "transactionType": "outcome",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

### DEV
GET http://localhost:8081/transactions/getAllTransactionsByDepotId/1

### DEV
GET http://localhost:8081/transactions/getThreeLatestTransactionByDepotId/1

### DEV
GET http://localhost:8081/transactions/getTransactionsId/1

### DEV
DELETE http://localhost:8081/transactions/deleteTransactionBy/1


### PROD
GET http://localhost:80/transactions-service/transactions/test

### PROD WENN localhost nicht klappt
POST http://192.168.80.15:8080/transactions-service/transactions
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "Master of Disaster",
  "iban": "DE89370400440532013XXX",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Stuff",
  "standingOrder": true,
  "transactionType": "income",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}

### PROD WENN localhost nicht klappt
POST http://localhost:80/transactions-service/transactions
Accept: application/json
Content-Type: application/json

{
  "depotId": 1,
  "country": "Germany",
  "recipient": "Master of Disaster",
  "iban": "DE89370400440532013XXX",
  "bic": "COBADEFFXXX",
  "moneyValue": 2500.00,
  "purposeOfUse": "Stuff",
  "standingOrder": true,
  "transactionType": "income",
  "transactionClassification": "Standard Überweisung",
  "dateTimeOfFirstExecution": "2024-01-01T10:00:00",
  "dateTimeOfLastExecution": "2024-06-01T10:00:00"
}


### PROD
GET http://localhost:80/transactions-service/transactions/getTransactionById/1

### PROD
GET http://localhost:80/transactions-service/transactions/getAllTransactionsByDepotId/1

### PROD
DELETE http://localhost:80/transactions-service/transactions/deleteTransactionBy/1

























