version: "3.8"

########################################################
# Volume Definition
########################################################
volumes:
  metrics-service-data:     # Volume to store metrics

services:
  ########################################################
  # Prometheus - Metrics Collector Service
  ########################################################
  metrics-service:
    image: prom/prometheus
    command:
      - --web.external-url=/metrics-service
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - metrics-service-data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prom.rule=PathPrefix(`/prometheus`)"
      - "traefik.http.services.prom.loadbalancer.server.port=9090"
      - "traefik.http.routers.prom.entrypoints=web"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge


