global:
  scrape_interval: 5s

  external_labels:
    monitor: 'system-monitor'

scrape_configs:
  - job_name: 'aurumbanking-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: [
        'customer-information-service:80',
        'transaction-service:80',
        'depot-service:80',
        'support-service:80',
        'login-service:80'
      ]
  - job_name: 'infrastructure'
    metrics_path: '/metrics'
    static_configs:
      - targets: [
        'gateway:80',
        'tracing-service:14269'
      ]
