entryPoints:
  web:
    address: :80
api:
  dashboard: true
metrics:
  prometheus: {}
tracing:
  serviceName: gateway
  spanNameLimit: 150
  jaeger:
    samplingServerURL: http://tracing-service:5778/sampling
    localAgentHostPort: tracing-service:6831
    collector:
      endpoint: http://tracing-service:14268/api/traces?format=jaeger.thrift